### ISSUE TITLE
Session become empty when using sinatra app

### ISSUE THREAD

**Issue by arunagw** [omniauth/omniauth-oauth#11]
Found something which needs to be looked.

Example: A sinatra app with having :session, true as a configuration. 

this will reset session as {} and an error raised on our callback_phase method where we are checking <code> raise OmniAuth::NoSessionError.new("Session Expired") if session['oauth'].nil? </code>

Any idea??

Without session config in sinatra it contains 

``` ruby

{"oauth"=>{"twitter"=>{"callback_confirmed"=>true, "request_token"=>"some token", "request_secret"=>"some secret"}}}

```

related issue here https://github.com/arunagw/omniauth-twitter/issues/42

**Comment by BobbyMcWho** [comment]
Closing as stale
