### ISSUE TITLE
Should subclasses be added to Strategies?

### ISSUE THREAD

**Issue by richseviora** [omniauth/omniauth-oauth#21]
`OmniAuth.strategies` should (I think?) include a list of all available strategies. However, descendants of `OmniAuth::Strategies::OAuth` aren't included because `OmniAuth::Strategy:: only is called for the first class including it, not its descendants.

`OmniAuth::Strategies::OAuth2` has a [fix](https://github.com/omniauth/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L17), I'm wondering if this should apply here as well?

**Comment by BobbyMcWho** [comment]
Feel free to open a PR if you like, I have no plans on implementing myself at the moment.
